const cards = {
  'warriors': [
    'assets/card_inventory/warriors/alexander3.png',
    'assets/card_inventory/warriors/andreas2.png',
    'assets/card_inventory/warriors/damaris5.png',
    'assets/card_inventory/warriors/darian6.png',
    'assets/card_inventory/warriors/isadora4.png',
    'assets/card_inventory/warriors/kallias2.png',
    'assets/card_inventory/warriors/kostas4.png',
    'assets/card_inventory/warriors/menelaus6.png',
    'assets/card_inventory/warriors/theron1.png',
  ],
  'creatures': [
    'assets/card_inventory/creatures/centaur2.png',
    'assets/card_inventory/creatures/chimera1.png',
    'assets/card_inventory/creatures/griffin4.png',
    'assets/card_inventory/creatures/harpy3.png',
    'assets/card_inventory/creatures/hydra4.png',
    'assets/card_inventory/creatures/medusa1.png',
    'assets/card_inventory/creatures/minotaur3.png',
    'assets/card_inventory/creatures/pegasus6.png',
    'assets/card_inventory/creatures/satyr5.png',
  ],
  'heroes': [
    'assets/card_inventory/heroes/antiope5.png',
    'assets/card_inventory/heroes/atalanta4.png',
    'assets/card_inventory/heroes/cassandra2.png',
    'assets/card_inventory/heroes/hector3.png',
    'assets/card_inventory/heroes/helen2.png',
    'assets/card_inventory/heroes/hercules3.png',
    'assets/card_inventory/heroes/jason6.png',
    'assets/card_inventory/heroes/leonidas1.png',
    'assets/card_inventory/heroes/achiles4.png',
  ],
  'titans': [
    'assets/card_inventory/titans/atlas3.png',
    'assets/card_inventory/titans/gaia2.png',
    'assets/card_inventory/titans/hyperion6.png',
    'assets/card_inventory/titans/kronos1.png',
    'assets/card_inventory/titans/perses5.png',
    'assets/card_inventory/titans/prometheus5.png',
    'assets/card_inventory/titans/rhea2.png',
    'assets/card_inventory/titans/themis4.png',
    'assets/card_inventory/titans/uranus3.png',
  ],
  'gods': [
    'assets/card_inventory/gods/aphrodite4.png',
    'assets/card_inventory/gods/artemis1.png',
    'assets/card_inventory/gods/athena3.png',
    'assets/card_inventory/gods/hades6.png',
    'assets/card_inventory/gods/hephaestus1.png',
    'assets/card_inventory/gods/hera4.png',
    'assets/card_inventory/gods/hermes2.png',
    'assets/card_inventory/gods/poseidon1.png',
    'assets/card_inventory/gods/zeus5.png',
  ]  
};  

export default cards; 
