const cards = {
  'warriors': [
    'card_inventory/warriors/alexander3',
    'card_inventory/warriors/andreas2',
    'card_inventory/warriors/damaris5',
    'card_inventory/warriors/darian6',
    'card_inventory/warriors/isadora4',
    'card_inventory/warriors/kallias2',
    'card_inventory/warriors/kostas4',
    'card_inventory/warriors/menelaus6',
    'card_inventory/warriors/theron1',
  ],
  'creatures': [
    'card_inventory/creatures/centaur2',
    'card_inventory/creatures/chimera1',
    'card_inventory/creatures/griffin4',
    'card_inventory/creatures/harpy3',
    'card_inventory/creatures/hydra4',
    'card_inventory/creatures/medusa1',
    'card_inventory/creatures/minotaur3',
    'card_inventory/creatures/pegasus6',
    'card_inventory/creatures/satyr5',
  ],
  'heroes': [
    'card_inventory/heroes/antiope5',
    'card_inventory/heroes/atalanta4',
    'card_inventory/heroes/cassandra2',
    'card_inventory/heroes/hector3',
    'card_inventory/heroes/helen2',
    'card_inventory/heroes/hercules3',
    'card_inventory/heroes/jason6',
    'card_inventory/heroes/leonidas1',
    'card_inventory/heroes/achiles4',
  ],
  'titans': [
    'card_inventory/titans/atlas3',
    'card_inventory/titans/gaia2',
    'card_inventory/titans/hyperion6',
    'card_inventory/titans/kronos1',
    'card_inventory/titans/perses5',
    'card_inventory/titans/prometheus5',
    'card_inventory/titans/rhea2',
    'card_inventory/titans/themis4',
    'card_inventory/titans/uranus3',
  ],
  'gods': [
    'card_inventory/gods/aphrodite4',
    'card_inventory/gods/artemis1',
    'card_inventory/gods/athena3',
    'card_inventory/gods/hades6',
    'card_inventory/gods/hephaestus1',
    'card_inventory/gods/hera4',
    'card_inventory/gods/hermes2',
    'card_inventory/gods/poseidon1',
    'card_inventory/gods/zeus5',
  ]  
};  

export default cards; 
